#!/usr/bin/env bash
# Verifies that the vendored ContentEdit/ContentSelect/HTMLString section of the
# frozen v1.6.16 artifact reproduces byte-for-byte from upstream CoffeeScript
# source. See UPSTREAM.md. Exits non-zero on any mismatch.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# The vendored bundle used to live at external/scripts/content-edit.js. The
# build now compiles it from vendor-src/, so that duplicate is gone -- but the
# identical bytes are the first 5560 lines of the frozen v1.6.16 artifact,
# which is what this check now compares against.
TARGET="$(mktemp)"; trap 'rm -f "$TARGET"' EXIT
head -5560 "$REPO_ROOT/build/content-tools.js" > "$TARGET"
EXPECTED_MD5="02110d6c67fcec34a8ce13d68241be10"

CE_SHA="8176f1d02ce083b7d23ef0b6249515324fa3a8da"   # ContentEdit 1.3.5
CS_SHA="3857dd67a96891a1bdb283d3a554a5b603883810"   # ContentSelect 1.0.3
HS_SHA="8ca1028b8f00c0ae20e25887e57999c7eb6fb03b"   # HTMLString 1.0.6

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK" "$TARGET"' EXIT
cd "$WORK"

echo "==> Installing CoffeeScript 1.7.1"
npm install --silent --no-save --prefix "$WORK/coffee" coffee-script@1.7.1 >/dev/null
COFFEE="$WORK/coffee/node_modules/.bin/coffee"

fetch() {  # fetch <name> <repo> <sha>
  git init -q "$2" && git -C "$2" remote add origin "https://github.com/GetmeUK/$2.git"
  git -C "$2" fetch -q --depth 1 origin "$3" && git -C "$2" checkout -q FETCH_HEAD
  echo "    $1 @ $3"
}
echo "==> Fetching upstream sources"
fetch "ContentEdit"   ContentEdit   "$CE_SHA"
fetch "ContentSelect" ContentSelect "$CS_SHA"
fetch "HTMLString"    HTMLString    "$HS_SHA"

# `join: true` == concatenate then compile (one shared closure). Order is load-bearing.
compile() { "$COFFEE" --join "$1" --compile "${@:2}" >/dev/null 2>&1
            grep -v '^// Generated by CoffeeScript' "$1" > "$1.clean"; }

echo "==> Compiling"
cd HTMLString
compile hs.js src/namespace.coffee src/strings.coffee src/tags.coffee src/characters.coffee
{ cat external/fsm.js; printf '\n'; cat hs.js.clean; } > "$WORK/html-string.js"
cd ../ContentSelect
compile cs.js src/content-select.coffee
cp cs.js.clean "$WORK/content-select.js"
cd ../ContentEdit
compile ce.js src/scripts/{namespace,tag-names,bases,regions,fixtures,root,static,text,images,videos,lists,tables}.coffee
cp ce.js.clean "$WORK/content-edit-only.js"

# grunt-contrib-concat joins with a single linefeed separator
cd "$WORK"
{ cat html-string.js; printf '\n'; cat content-select.js; printf '\n'; cat content-edit-only.js; } > rebuilt.js

echo "==> Comparing"
ACTUAL_MD5="$(md5sum < rebuilt.js | cut -d' ' -f1)"
if [ "$ACTUAL_MD5" != "$EXPECTED_MD5" ]; then
  echo "FAIL: rebuilt md5 $ACTUAL_MD5 != expected $EXPECTED_MD5"; exit 1
fi
if ! diff -q rebuilt.js "$TARGET" >/dev/null; then
  echo "FAIL: rebuilt output differs from the frozen v1.6.16 vendored section"; diff rebuilt.js "$TARGET" | head -40; exit 1
fi
echo "OK: reproduces byte-for-byte (md5 $ACTUAL_MD5)"
