/* Phase 1 build shim.
 *
 * The library is still CoffeeScript compiled under the `join: true` model --
 * all files are concatenated and THEN compiled, so every class shares one
 * closure and the order below is load-bearing. Vite cannot express that, and
 * Phase 3 is where the source becomes real ESM modules. Until then this
 * reproduces exactly what Grunt did, so the golden master keeps a build to
 * run against.
 *
 * Order recovered verbatim from the deleted Gruntfile.coffee (coffee.build).
 */
import {execFileSync} from 'node:child_process';
import {mkdirSync, readFileSync, writeFileSync, rmSync} from 'node:fs';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const OUT = join(ROOT, 'dist');
const TMP = join(ROOT, 'src/tmp');

const SOURCES = [
    'namespace',
    // UI
    'ui/ui', 'ui/events', 'ui/flashes', 'ui/ignition', 'ui/inspector',
    'ui/modal', 'ui/toolbox',
    // UI - Dialogs
    'ui/dialogs/dialogs', 'ui/dialogs/image', 'ui/dialogs/link',
    'ui/dialogs/properties', 'ui/dialogs/table', 'ui/dialogs/video',
    // Other
    'clean-html', 'editor', 'history', 'styles', 'tools'
].map(n => join(ROOT, 'src/scripts', `${n}.coffee`));

mkdirSync(TMP, {recursive: true});
mkdirSync(OUT, {recursive: true});

// `coffee --join` == concatenate then compile: one shared closure.
const require_ = createRequire(import.meta.url);
// Pinned to coffee-script 1.7.1 -- the compiler the committed v1.6.16 build
// used. 1.9+ renamed the generated helpers (__slice -> slice, __extends ->
// extend, _ref -> ref), which produces ~700 lines of purely cosmetic diff and
// destroys the byte-for-byte equivalence check this phase relies on.
const coffeeBin = join(dirname(require_.resolve('coffee-script/package.json')), 'bin/coffee');
const joined = join(TMP, 'content-tools.js');
execFileSync(process.execPath, [coffeeBin, '--join', joined, '--compile', ...SOURCES],
             {cwd: ROOT, stdio: 'inherit'});

// ContentEdit + ContentSelect + HTMLString + FSM still ship as one prebuilt
// bundle prepended to our output; Phase 3 absorbs them as real modules.
const vendor = readFileSync(join(ROOT, 'external/scripts/content-edit.js'), 'utf8');
const compiled = readFileSync(joined, 'utf8');

// The unminified legacy artifact carries no banner (that lives on the .min).
// Strip the compiler's own "Generated by" line for the same reason.
writeFileSync(join(OUT, 'content-tools.js'),
              vendor + '\n' + compiled.replace(/^\/\/ Generated by CoffeeScript.*\n/gm, ''));
rmSync(TMP, {recursive: true, force: true});

console.log(`built dist/content-tools.js`);
