/* Builds dist/content-tools.js from CoffeeScript source.
 *
 * Every library -- ContentTools and the three it was built on -- now compiles
 * from source in this repo; nothing is taken from a prebuilt bundle.
 *
 * Two compile modes, selected with --mixed:
 *
 *   join  (default)  Concatenate a unit's .coffee files and compile them as
 *                    one translation unit, exactly as the original Gruntfiles
 *                    did. Reproduces the v1.6.16 artifact byte for byte.
 *
 *   mixed            Compile each file separately with --bare and concatenate
 *                    the chunks inside one IIFE. Verified token-for-token
 *                    identical to `join` once whitespace and hoisted
 *                    declarations are normalised -- declaration *placement*
 *                    moves, which is meaningless inside one function scope.
 *                    Crucially this lets a file be supplied as .js instead of
 *                    .coffee, so the CoffeeScript -> JavaScript conversion can
 *                    proceed one file at a time and any file can be flipped
 *                    back independently to isolate a regression.
 */
import {execFileSync} from 'node:child_process';
import {existsSync, mkdirSync, readFileSync, writeFileSync, rmSync} from 'node:fs';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {PREAMBLE, UNITS} from './sources.mjs';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const OUT = join(ROOT, 'dist');
const TMP = join(ROOT, 'src/tmp');
const MIXED = process.argv.includes('--mixed');

// Pinned to coffee-script 1.7.1 -- the compiler the committed v1.6.16 build
// used. 1.9+ renamed the generated helpers (__slice -> slice, __extends ->
// extend, _ref -> ref), which produces ~700 lines of purely cosmetic diff and
// destroys the byte-for-byte equivalence check.
const require_ = createRequire(import.meta.url);
const COFFEE = join(dirname(require_.resolve('coffee-script/package.json')), 'bin/coffee');

const stripBanner = s => s.replace(/^\/\/ Generated by CoffeeScript.*\n/gm, '');

/** Compile a unit's files together, in one shared closure (original behaviour). */
function buildJoined(unit) {
    const out = join(TMP, `${unit.name}.js`);
    const files = unit.files.map(f => join(ROOT, unit.dir, `${f}.coffee`));
    execFileSync(process.execPath, [COFFEE, '--join', out, '--compile', ...files],
                 {cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit']});
    return stripBanner(readFileSync(out, 'utf8'));
}

/** Compile each file on its own and wrap the concatenation in one IIFE. */
function buildMixed(unit) {
    const chunks = unit.files.map(f => {
        const js = join(ROOT, unit.dir, `${f}.js`);
        // A converted file wins over its CoffeeScript original, which is what
        // makes the conversion incremental and reversible per file.
        if (existsSync(js)) return readFileSync(js, 'utf8');
        const coffee = join(ROOT, unit.dir, `${f}.coffee`);
        return stripBanner(execFileSync(
            process.execPath, [COFFEE, '--bare', '--print', '--compile', coffee],
            {cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit']}));
    });
    // Do NOT declare shared names here: if a converted file uses `let`/`const`
    // for one, a `var` of the same name in this wrapper is a redeclaration
    // SyntaxError. Same-block visibility already covers it.
    return `(function() {\n${chunks.join('\n')}\n}).call(this);\n`;
}

mkdirSync(TMP, {recursive: true});
mkdirSync(OUT, {recursive: true});

const parts = PREAMBLE.map(p => readFileSync(join(ROOT, p), 'utf8'))
    .concat(UNITS.map(MIXED ? buildMixed : buildJoined));

// grunt-contrib-concat joined these with a single linefeed.
writeFileSync(join(OUT, 'content-tools.js'), parts.join('\n'));
rmSync(TMP, {recursive: true, force: true});

console.log(`built dist/content-tools.js (${MIXED ? 'mixed' : 'join'} mode)`);
